Repository hackbeats/complete-web3-bootcamp, pull requests merged in 2022-10, with the labels that each got.

#5 Add README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#6 Added 5 Beginner Friendly Topics
  Topics.md
  beginner_project.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#8 web3 articles addition
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#13 updated learning resources
  README.md
Labels: good first issue, hacktoberfest, hacktober-accepted

#29 Update Topics.md
  Topics.md
Labels: enhancement, good first issue, hacktoberfest, hacktober-accepted

#26 adding chainlink bootcamp to learning resources section
  README.md
Labels: good first issue, hacktoberfest, hacktober-accepted

#25 Update contribution.md
  CONTRIBUTING.md
  README.md
Labels: good first issue, hacktoberfest, hacktober-accepted

#34 added polygon white paper
  README.md
Labels: good first issue, hacktoberfest, hacktober-accepted

#41 add Near White paper
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#42 added celo white papers
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#43 added Deso chain white papers
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#45 Added Developer DAO in the Communities Section
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#46 added popular web3 communities
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#48 Fixing discord link
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#50 add super team dao
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober-accepted

#52 added questbook
  README.md
Labels: good first issue, hacktoberfest, hacktober-accepted
